import type { FilterDropdownOption } from "@/lib/books";

// Generated from all_genres_with_counts.txt (distinct genres from books.genres)
// Total distinct genres: 1364
export const ALL_GENRE_OPTIONS: FilterDropdownOption[] = [
  { value: "10th Century", label: "10th Century", count: 166 },
  { value: "11th Century", label: "11th Century", count: 848 },
  { value: "12th Century", label: "12th Century", count: 2467 },
  { value: "13th Century", label: "13th Century", count: 3064 },
  { value: "14th Century", label: "14th Century", count: 9991 },
  { value: "15th Century", label: "15th Century", count: 4929 },
  { value: "16th Century", label: "16th Century", count: 18658 },
  { value: "17th Century", label: "17th Century", count: 29574 },
  { value: "18th Century", label: "18th Century", count: 101946 },
  { value: "1917", label: "1917", count: 130 },
  { value: "19th Century", label: "19th Century", count: 1184885 },
  { value: "1st Grade", label: "1st Grade", count: 14758 },
  { value: "20th Century", label: "20th Century", count: 578492 },
  { value: "21st Century", label: "21st Century", count: 26509 },
  { value: "2nd Grade", label: "2nd Grade", count: 13164 },
  { value: "40k", label: "40k", count: 4043 },
  { value: "Aapi", label: "Aapi", count: 1114 },
  { value: "Abuse", label: "Abuse", count: 54554 },
  { value: "Academia", label: "Academia", count: 4093 },
  { value: "Academic", label: "Academic", count: 73986 },
  { value: "Academics", label: "Academics", count: 1701 },
  { value: "Accounting", label: "Accounting", count: 1465 },
  { value: "Action", label: "Action", count: 265831 },
  { value: "Activism", label: "Activism", count: 7446 },
  { value: "Adaptations", label: "Adaptations", count: 176 },
  { value: "Addiction", label: "Addiction", count: 10874 },
  { value: "Addition", label: "Addition", count: 55 },
  { value: "Adhd", label: "Adhd", count: 3134 },
  { value: "Adolescence", label: "Adolescence", count: 383 },
  { value: "Adoption", label: "Adoption", count: 7414 },
  { value: "Adult", label: "Adult", count: 828462 },
  { value: "Adult Colouring Books", label: "Adult Colouring Books", count: 192 },
  { value: "Adult Fiction", label: "Adult Fiction", count: 219400 },
  { value: "Adventure", label: "Adventure", count: 1589479 },
  { value: "Aeroplanes", label: "Aeroplanes", count: 385 },
  { value: "Africa", label: "Africa", count: 121950 },
  { value: "African American", label: "African American", count: 108277 },
  { value: "African American Literature", label: "African American Literature", count: 6628 },
  { value: "African American Romance", label: "African American Romance", count: 9551 },
  { value: "African Literature", label: "African Literature", count: 10625 },
  { value: "Agatha Christie", label: "Agatha Christie", count: 60399 },
  { value: "Age Gap Romance", label: "Age Gap Romance", count: 1781 },
  { value: "Agriculture", label: "Agriculture", count: 3355 },
  { value: "Aircraft", label: "Aircraft", count: 92 },
  { value: "Airships", label: "Airships", count: 19 },
  { value: "Albanian Literature", label: "Albanian Literature", count: 908 },
  { value: "Alchemy", label: "Alchemy", count: 3597 },
  { value: "Alcohol", label: "Alcohol", count: 4035 },
  { value: "Alexandria", label: "Alexandria", count: 83 },
  { value: "Algebra", label: "Algebra", count: 309 },
  { value: "Algeria", label: "Algeria", count: 1712 },
  { value: "Algorithms", label: "Algorithms", count: 493 },
  { value: "Aliens", label: "Aliens", count: 81355 },
  { value: "Alternate History", label: "Alternate History", count: 18535 },
  { value: "Alternate Universe", label: "Alternate Universe", count: 326 },
  { value: "Alternative Medicine", label: "Alternative Medicine", count: 628 },
  { value: "Amateur Sleuth", label: "Amateur Sleuth", count: 3898 },
  { value: "Amazon", label: "Amazon", count: 115128 },
  { value: "American", label: "American", count: 604881 },
  { value: "Americana", label: "Americana", count: 24397 },
  { value: "American Civil War", label: "American Civil War", count: 19837 },
  { value: "American Classics", label: "American Classics", count: 3441 },
  { value: "American Fiction", label: "American Fiction", count: 5332 },
  { value: "American History", label: "American History", count: 188490 },
  { value: "American Revolution", label: "American Revolution", count: 21092 },
  { value: "American Revolutionary War", label: "American Revolutionary War", count: 8415 },
  { value: "Amish", label: "Amish", count: 14531 },
  { value: "Amish Fiction", label: "Amish Fiction", count: 10986 },
  { value: "Anarchism", label: "Anarchism", count: 3740 },
  { value: "Ancient", label: "Ancient", count: 122957 },
  { value: "Ancient History", label: "Ancient History", count: 102795 },
  { value: "Angels", label: "Angels", count: 23011 },
  { value: "Anglo Saxon", label: "Anglo Saxon", count: 1158 },
  { value: "Angola", label: "Angola", count: 1020 },
  { value: "Animal Fiction", label: "Animal Fiction", count: 9415 },
  { value: "Animals", label: "Animals", count: 369007 },
  { value: "Anime", label: "Anime", count: 5851 },
  { value: "Anthologies", label: "Anthologies", count: 106239 },
  { value: "Anthropology", label: "Anthropology", count: 68465 },
  { value: "Anthropomorphic", label: "Anthropomorphic", count: 789 },
  { value: "Anti Racist", label: "Anti Racist", count: 5925 },
  { value: "Antisemitism", label: "Antisemitism", count: 323 },
  { value: "Apocalyptic", label: "Apocalyptic", count: 30229 },
  { value: "Apple", label: "Apple", count: 1002 },
  { value: "Applied Mathematics", label: "Applied Mathematics", count: 15 },
  { value: "Archaeology", label: "Archaeology", count: 12453 },
  { value: "Architecture", label: "Architecture", count: 15113 },
  { value: "Arithmetic", label: "Arithmetic", count: 51 },
  { value: "Art", label: "Art", count: 170729 },
  { value: "Art and Photography", label: "Art and Photography", count: 3678 },
  { value: "Art Books Monographs", label: "Art Books Monographs", count: 17 },
  { value: "Art Design", label: "Art Design", count: 10851 },
  { value: "Art History", label: "Art History", count: 24167 },
  { value: "Arthurian", label: "Arthurian", count: 22759 },
  { value: "Artificial Intelligence", label: "Artificial Intelligence", count: 7644 },
  { value: "Asexual", label: "Asexual", count: 529 },
  { value: "Asia", label: "Asia", count: 123045 },
  { value: "Asian American", label: "Asian American", count: 4083 },
  { value: "Asian Literature", label: "Asian Literature", count: 37543 },
  { value: "Aspergers", label: "Aspergers", count: 636 },
  { value: "Astrology", label: "Astrology", count: 2020 },
  { value: "Astronomy", label: "Astronomy", count: 14781 },
  { value: "Atheism", label: "Atheism", count: 17186 },
  { value: "Atlases", label: "Atlases", count: 258 },
  { value: "Audiobook", label: "Audiobook", count: 4200935 },
  { value: "Australia", label: "Australia", count: 44984 },
  { value: "Autistic Spectrum Disorder", label: "Autistic Spectrum Disorder", count: 8138 },
  { value: "Autobiography", label: "Autobiography", count: 256933 },
  { value: "Aviation", label: "Aviation", count: 15447 },
  { value: "Aviation History", label: "Aviation History", count: 43 },
  { value: "Babylon 5", label: "Babylon 5", count: 68 },
  { value: "Back To School", label: "Back To School", count: 2459 },
  { value: "Baha I", label: "Baha I", count: 156 },
  { value: "Bande Dessinée", label: "Bande Dessinée", count: 34717 },
  { value: "Bangladesh", label: "Bangladesh", count: 953 },
  { value: "Banking", label: "Banking", count: 1550 },
  { value: "Banks", label: "Banks", count: 918 },
  { value: "Banned Books", label: "Banned Books", count: 37565 },
  { value: "Baseball", label: "Baseball", count: 12255 },
  { value: "Basketball", label: "Basketball", count: 4565 },
  { value: "Batman", label: "Batman", count: 9946 },
  { value: "Battle Of Britain", label: "Battle Of Britain", count: 230 },
  { value: "BDSM", label: "BDSM", count: 53429 },
  { value: "Beach Reads", label: "Beach Reads", count: 6908 },
  { value: "Beauty and The Beast", label: "Beauty and The Beast", count: 4974 },
  { value: "Beer", label: "Beer", count: 561 },
  { value: "Belgian", label: "Belgian", count: 5273 },
  { value: "Belgium", label: "Belgium", count: 7478 },
  { value: "Belief", label: "Belief", count: 251 },
  { value: "Beverages", label: "Beverages", count: 95 },
  { value: "Biblical", label: "Biblical", count: 6026 },
  { value: "Biblical Fiction", label: "Biblical Fiction", count: 6402 },
  { value: "Biblical Studies", label: "Biblical Studies", count: 7616 },
  { value: "Bicycles", label: "Bicycles", count: 939 },
  { value: "Bigfoot", label: "Bigfoot", count: 163 },
  { value: "Billionaire Romance", label: "Billionaire Romance", count: 9358 },
  { value: "Billionaires", label: "Billionaires", count: 5867 },
  { value: "Biographical Fiction", label: "Biographical Fiction", count: 1677 },
  { value: "Biography", label: "Biography", count: 775716 },
  { value: "Biography Memoir", label: "Biography Memoir", count: 346983 },
  { value: "Biology", label: "Biology", count: 71801 },
  { value: "Birds", label: "Birds", count: 13878 },
  { value: "Bird Watching", label: "Bird Watching", count: 12 },
  { value: "Bisexual", label: "Bisexual", count: 1573 },
  { value: "Bisexual Romance", label: "Bisexual Romance", count: 5 },
  { value: "Bizarro Fiction", label: "Bizarro Fiction", count: 623 },
  { value: "Black Historical Fiction", label: "Black Historical Fiction", count: 86 },
  { value: "Black Literature", label: "Black Literature", count: 925 },
  { value: "Boarding School", label: "Boarding School", count: 8960 },
  { value: "Boating", label: "Boating", count: 14 },
  { value: "Bodies", label: "Bodies", count: 3933 },
  { value: "Bodyguard Romance", label: "Bodyguard Romance", count: 484 },
  { value: "Bolivia", label: "Bolivia", count: 617 },
  { value: "Bombers", label: "Bombers", count: 2 },
  { value: "Book Club", label: "Book Club", count: 752619 },
  { value: "Books About Books", label: "Books About Books", count: 53143 },
  { value: "Booze", label: "Booze", count: 614 },
  { value: "Borrowed", label: "Borrowed", count: 28 },
  { value: "Botswana", label: "Botswana", count: 2226 },
  { value: "Boxers", label: "Boxers", count: 18 },
  { value: "Boys Love", label: "Boys Love", count: 5893 },
  { value: "Brain", label: "Brain", count: 11951 },
  { value: "Brazil", label: "Brazil", count: 17618 },
  { value: "Brewing", label: "Brewing", count: 480 },
  { value: "British Literature", label: "British Literature", count: 1026256 },
  { value: "British Royalty", label: "British Royalty", count: 109 },
  { value: "Buddhism", label: "Buddhism", count: 34288 },
  { value: "Buffy The Vampire Slayer", label: "Buffy The Vampire Slayer", count: 1251 },
  { value: "Buisness", label: "Buisness", count: 30874 },
  { value: "Bulgaria", label: "Bulgaria", count: 2094 },
  { value: "Bulgarian Literature", label: "Bulgarian Literature", count: 1767 },
  { value: "Burkina Faso", label: "Burkina Faso", count: 85 },
  { value: "Burundi", label: "Burundi", count: 160 },
  { value: "Buses", label: "Buses", count: 151 },
  { value: "Business", label: "Business", count: 265025 },
  { value: "Business Ethics", label: "Business Ethics", count: 26 },
  { value: "Business Leadership", label: "Business Leadership", count: 3689 },
  { value: "Business Strategy", label: "Business Strategy", count: 1235 },
  { value: "Butch Femme", label: "Butch Femme", count: 1189 },
  { value: "Cabo Verde", label: "Cabo Verde", count: 3 },
  { value: "Cairo", label: "Cairo", count: 206 },
  { value: "Calculus", label: "Calculus", count: 900 },
  { value: "Cameroon", label: "Cameroon", count: 317 },
  { value: "Campus", label: "Campus", count: 275 },
  { value: "Canada", label: "Canada", count: 139572 },
  { value: "Canadian Literature", label: "Canadian Literature", count: 12791 },
  { value: "Canon", label: "Canon", count: 4741 },
  { value: "Cape Town", label: "Cape Town", count: 41 },
  { value: "Cars", label: "Cars", count: 1772 },
  { value: "Cartography", label: "Cartography", count: 450 },
  { value: "Cartoon", label: "Cartoon", count: 2629 },
  { value: "Category Romance", label: "Category Romance", count: 7727 },
  { value: "Catholic", label: "Catholic", count: 66820 },
  { value: "Cats", label: "Cats", count: 39671 },
  { value: "Celebrity", label: "Celebrity", count: 13614 },
  { value: "Celebrity Romance", label: "Celebrity Romance", count: 756 },
  { value: "Central Africa", label: "Central Africa", count: 19 },
  { value: "Central African Republic", label: "Central African Republic", count: 11 },
  { value: "Chad", label: "Chad", count: 135 },
  { value: "Challenged Books", label: "Challenged Books", count: 65 },
  { value: "Chapter Books", label: "Chapter Books", count: 80034 },
  { value: "Chemistry", label: "Chemistry", count: 5084 },
  { value: "Chess", label: "Chess", count: 3238 },
  { value: "Chick Lit", label: "Chick Lit", count: 295991 },
  { value: "Child Psychology", label: "Child Psychology", count: 258 },
  { value: "Childrens", label: "Childrens", count: 1344276 },
  { value: "Childrens Classics", label: "Childrens Classics", count: 66260 },
  { value: "Childrens Mystery", label: "Childrens Mystery", count: 230 },
  { value: "Children S Mystery", label: "Children S Mystery", count: 7 },
  { value: "China", label: "China", count: 66446 },
  { value: "Chinese Literature", label: "Chinese Literature", count: 11871 },
  { value: "Chivalry", label: "Chivalry", count: 163 },
  { value: "Choose Your Own Adventure", label: "Choose Your Own Adventure", count: 1104 },
  { value: "Christian", label: "Christian", count: 467328 },
  { value: "Christian Contemporary Fiction", label: "Christian Contemporary Fiction", count: 32 },
  { value: "Christian Fantasy", label: "Christian Fantasy", count: 2978 },
  { value: "Christian Fiction", label: "Christian Fiction", count: 170662 },
  { value: "Christian Fiction Amish", label: "Christian Fiction Amish", count: 58 },
  { value: "Christian Historical Fiction", label: "Christian Historical Fiction", count: 10250 },
  { value: "Christian History", label: "Christian History", count: 794 },
  { value: "Christianity", label: "Christianity", count: 302004 },
  { value: "Christian Living", label: "Christian Living", count: 105805 },
  { value: "Christian Non Fiction", label: "Christian Non Fiction", count: 59247 },
  { value: "Christian Romance", label: "Christian Romance", count: 46612 },
  { value: "Christian Romance Historical", label: "Christian Romance Historical", count: 4 },
  { value: "Christmas", label: "Christmas", count: 118414 },
  { value: "Church", label: "Church", count: 19614 },
  { value: "Church History", label: "Church History", count: 19056 },
  { value: "Church Ministry", label: "Church Ministry", count: 675 },
  { value: "Cinderella", label: "Cinderella", count: 2060 },
  { value: "Cities", label: "Cities", count: 5725 },
  { value: "Civil Engineering", label: "Civil Engineering", count: 183 },
  { value: "Civil War", label: "Civil War", count: 39255 },
  { value: "Civil War Confederacy", label: "Civil War Confederacy", count: 20 },
  { value: "Civil War Eastern Theater", label: "Civil War Eastern Theater", count: 226 },
  { value: "Civil War History", label: "Civil War History", count: 1023 },
  { value: "Civil War Western Theater", label: "Civil War Western Theater", count: 155 },
  { value: "Class", label: "Class", count: 1218 },
  { value: "Classical Music", label: "Classical Music", count: 1986 },
  { value: "Classical Studies", label: "Classical Studies", count: 9165 },
  { value: "Classic Literature", label: "Classic Literature", count: 597049 },
  { value: "Classics", label: "Classics", count: 5124823 },
  { value: "Class Issues", label: "Class Issues", count: 13 },
  { value: "Clean Romance", label: "Clean Romance", count: 30605 },
  { value: "Climate Change", label: "Climate Change", count: 8536 },
  { value: "Climate Change Fiction", label: "Climate Change Fiction", count: 883 },
  { value: "Climbing", label: "Climbing", count: 3081 },
  { value: "Cocktails", label: "Cocktails", count: 338 },
  { value: "Coding", label: "Coding", count: 5682 },
  { value: "Coffee Table Books", label: "Coffee Table Books", count: 1860 },
  { value: "Coin Collecting", label: "Coin Collecting", count: 191 },
  { value: "Collections", label: "Collections", count: 76819 },
  { value: "Colleen Hoover", label: "Colleen Hoover", count: 1765 },
  { value: "College", label: "College", count: 76733 },
  { value: "College Romance", label: "College Romance", count: 13786 },
  { value: "Colouring", label: "Colouring", count: 252 },
  { value: "Colouring Books", label: "Colouring Books", count: 353 },
  { value: "Comedian", label: "Comedian", count: 841 },
  { value: "Comedy", label: "Comedy", count: 167497 },
  { value: "Comic Book", label: "Comic Book", count: 91015 },
  { value: "Comic Fantasy", label: "Comic Fantasy", count: 749 },
  { value: "Comics", label: "Comics", count: 290447 },
  { value: "Comics Bd", label: "Comics Bd", count: 1873 },
  { value: "Comics Manga", label: "Comics Manga", count: 77833 },
  { value: "Comic Strips", label: "Comic Strips", count: 3415 },
  { value: "Coming Of Age", label: "Coming Of Age", count: 103425 },
  { value: "Comix", label: "Comix", count: 9961 },
  { value: "Communication", label: "Communication", count: 28712 },
  { value: "Comoros", label: "Comoros", count: 5 },
  { value: "Computation", label: "Computation", count: 79 },
  { value: "Computers", label: "Computers", count: 13511 },
  { value: "Computer Science", label: "Computer Science", count: 18568 },
  { value: "Conservation", label: "Conservation", count: 1813 },
  { value: "Conspiracy Theories", label: "Conspiracy Theories", count: 8627 },
  { value: "Construction", label: "Construction", count: 1743 },
  { value: "Contemporary", label: "Contemporary", count: 1229839 },
  { value: "Contemporary History", label: "Contemporary History", count: 313 },
  { value: "Contemporary Romance", label: "Contemporary Romance", count: 502963 },
  { value: "Cookbooks", label: "Cookbooks", count: 31245 },
  { value: "Cooking", label: "Cooking", count: 38176 },
  { value: "Coptic Language", label: "Coptic Language", count: 3 },
  { value: "Costume History", label: "Costume History", count: 32 },
  { value: "Counselling", label: "Counselling", count: 22116 },
  { value: "Counter Culture", label: "Counter Culture", count: 964 },
  { value: "Counting", label: "Counting", count: 5887 },
  { value: "Courtroom Drama", label: "Courtroom Drama", count: 769 },
  { value: "Couture", label: "Couture", count: 8 },
  { value: "Cowboy Romance", label: "Cowboy Romance", count: 6216 },
  { value: "Cozy", label: "Cozy", count: 90584 },
  { value: "Cozy Fantasy", label: "Cozy Fantasy", count: 1875 },
  { value: "Cozy Fiction", label: "Cozy Fiction", count: 10 },
  { value: "Cozy Mystery", label: "Cozy Mystery", count: 128381 },
  { value: "Cozy Romance", label: "Cozy Romance", count: 137 },
  { value: "Crafts", label: "Crafts", count: 16891 },
  { value: "Creation Science", label: "Creation Science", count: 223 },
  { value: "Creative", label: "Creative", count: 3869 },
  { value: "Crime", label: "Crime", count: 1069363 },
  { value: "Criticism", label: "Criticism", count: 22951 },
  { value: "Crochet", label: "Crochet", count: 572 },
  { value: "Cross Dressing", label: "Cross Dressing", count: 436 },
  { value: "Cryonics", label: "Cryonics", count: 47 },
  { value: "Cryptids", label: "Cryptids", count: 231 },
  { value: "Cryptozoology", label: "Cryptozoology", count: 233 },
  { value: "Cthulhu Mythos", label: "Cthulhu Mythos", count: 10689 },
  { value: "Cuisine", label: "Cuisine", count: 2548 },
  { value: "Culinary", label: "Culinary", count: 11632 },
  { value: "Cult Classics", label: "Cult Classics", count: 1762 },
  { value: "Cults", label: "Cults", count: 4548 },
  { value: "Cultural", label: "Cultural", count: 89863 },
  { value: "Cultural Heritage", label: "Cultural Heritage", count: 154 },
  { value: "Cultural Studies", label: "Cultural Studies", count: 4039 },
  { value: "Curation", label: "Curation", count: 31 },
  { value: "Currency", label: "Currency", count: 23 },
  { value: "Current Affairs", label: "Current Affairs", count: 7934 },
  { value: "Cyberpunk", label: "Cyberpunk", count: 13575 },
  { value: "Cycling", label: "Cycling", count: 2242 },
  { value: "Czech Literature", label: "Czech Literature", count: 15298 },
  { value: "Danish", label: "Danish", count: 10857 },
  { value: "Dark", label: "Dark", count: 90809 },
  { value: "Dark Academia", label: "Dark Academia", count: 28089 },
  { value: "Dark Comedy", label: "Dark Comedy", count: 56 },
  { value: "Dark Fantasy", label: "Dark Fantasy", count: 21480 },
  { value: "Dark Humor", label: "Dark Humor", count: 202 },
  { value: "Dark Romance", label: "Dark Romance", count: 74699 },
  { value: "Dc Comics", label: "Dc Comics", count: 20452 },
  { value: "Death", label: "Death", count: 31505 },
  { value: "Deception", label: "Deception", count: 287 },
  { value: "Democratic Republic Of The Congo", label: "Democratic Republic Of The Congo", count: 89 },
  { value: "Demons", label: "Demons", count: 40420 },
  { value: "Denmark", label: "Denmark", count: 9500 },
  { value: "Dentistry", label: "Dentistry", count: 54 },
  { value: "Design", label: "Design", count: 28853 },
  { value: "Detective", label: "Detective", count: 480065 },
  { value: "Developmental Psychology", label: "Developmental Psychology", count: 93 },
  { value: "Devotional", label: "Devotional", count: 24212 },
  { value: "Diary", label: "Diary", count: 11081 },
  { value: "Dictionaries", label: "Dictionaries", count: 2027 },
  { value: "Did Not Finish", label: "Did Not Finish", count: 48 },
  { value: "Diets", label: "Diets", count: 7771 },
  { value: "Dinosaurs", label: "Dinosaurs", count: 24011 },
  { value: "Disability", label: "Disability", count: 26055 },
  { value: "Disability Studies", label: "Disability Studies", count: 675 },
  { value: "Discipleship", label: "Discipleship", count: 12046 },
  { value: "Disease", label: "Disease", count: 1525 },
  { value: "Divination", label: "Divination", count: 1787 },
  { value: "Division", label: "Division", count: 164 },
  { value: "Divorce", label: "Divorce", count: 2466 },
  { value: "Djibouti", label: "Djibouti", count: 21 },
  { value: "Doctors", label: "Doctors", count: 3361 },
  { value: "Doctor Who", label: "Doctor Who", count: 3085 },
  { value: "Documentaries", label: "Documentaries", count: 11 },
  { value: "Dogs", label: "Dogs", count: 53990 },
  { value: "Domestic", label: "Domestic", count: 821 },
  { value: "Domestic Fiction", label: "Domestic Fiction", count: 513 },
  { value: "Domestic Suspense", label: "Domestic Suspense", count: 109 },
  { value: "Domestic Thriller", label: "Domestic Thriller", count: 1117 },
  { value: "Downton Abbey", label: "Downton Abbey", count: 299 },
  { value: "Drag", label: "Drag", count: 102 },
  { value: "Dragonlance", label: "Dragonlance", count: 2077 },
  { value: "Dragons", label: "Dragons", count: 73181 },
  { value: "Drama", label: "Drama", count: 492424 },
  { value: "Dramedy", label: "Dramedy", count: 19 },
  { value: "Drawing", label: "Drawing", count: 4023 },
  { value: "Dressmaking", label: "Dressmaking", count: 70 },
  { value: "Drinking", label: "Drinking", count: 225 },
  { value: "Drugs", label: "Drugs", count: 13045 },
  { value: "Dual Timeline", label: "Dual Timeline", count: 1266 },
  { value: "Dungeons and Dragons", label: "Dungeons and Dragons", count: 6495 },
  { value: "Dutch Literature", label: "Dutch Literature", count: 5609 },
  { value: "Dying Earth", label: "Dying Earth", count: 1251 },
  { value: "Dystopia", label: "Dystopia", count: 181370 },
  { value: "Earth", label: "Earth", count: 583 },
  { value: "Earth Sciences", label: "Earth Sciences", count: 613 },
  { value: "Eastern Africa", label: "Eastern Africa", count: 103 },
  { value: "Eastern Philosophy", label: "Eastern Philosophy", count: 11451 },
  { value: "Ebooks", label: "Ebooks", count: 416840 },
  { value: "Ecclesiology", label: "Ecclesiology", count: 3400 },
  { value: "Ecology", label: "Ecology", count: 15890 },
  { value: "Economic Development", label: "Economic Development", count: 270 },
  { value: "Economics", label: "Economics", count: 156129 },
  { value: "Education", label: "Education", count: 114039 },
  { value: "Edwardian", label: "Edwardian", count: 2384 },
  { value: "Egypt", label: "Egypt", count: 24504 },
  { value: "Egyptian Literature", label: "Egyptian Literature", count: 2723 },
  { value: "Egyptology", label: "Egyptology", count: 2711 },
  { value: "Electrical Engineering", label: "Electrical Engineering", count: 463 },
  { value: "Elizabethan Period", label: "Elizabethan Period", count: 508 },
  { value: "Elves", label: "Elves", count: 2994 },
  { value: "Emergency Services", label: "Emergency Services", count: 47 },
  { value: "Emotion", label: "Emotion", count: 10201 },
  { value: "Emotional", label: "Emotional", count: 14650 },
  { value: "Emotional Romance", label: "Emotional Romance", count: 24 },
  { value: "Empiricism", label: "Empiricism", count: 12765 },
  { value: "Enemies To Lovers", label: "Enemies To Lovers", count: 107228 },
  { value: "Engineering", label: "Engineering", count: 12540 },
  { value: "English Civil War", label: "English Civil War", count: 372 },
  { value: "English Literature", label: "English Literature", count: 116486 },
  { value: "Entrepreneurship", label: "Entrepreneurship", count: 33987 },
  { value: "Environment", label: "Environment", count: 57462 },
  { value: "Environmental Science", label: "Environmental Science", count: 114 },
  { value: "Epic", label: "Epic", count: 42376 },
  { value: "Epic Fantasy", label: "Epic Fantasy", count: 81441 },
  { value: "Epic Poetry", label: "Epic Poetry", count: 1233 },
  { value: "Equality", label: "Equality", count: 75 },
  { value: "Equatorial Guinea", label: "Equatorial Guinea", count: 114 },
  { value: "Eritrea", label: "Eritrea", count: 219 },
  { value: "Erotica", label: "Erotica", count: 153835 },
  { value: "Erotic Historical Romance", label: "Erotic Historical Romance", count: 275 },
  { value: "Erotic Horror", label: "Erotic Horror", count: 331 },
  { value: "Erotic Paranormal Romance", label: "Erotic Paranormal Romance", count: 17 },
  { value: "Erotic Romance", label: "Erotic Romance", count: 53927 },
  { value: "Esoterica", label: "Esoterica", count: 8786 },
  { value: "Esp", label: "Esp", count: 1451 },
  { value: "Espionage", label: "Espionage", count: 99448 },
  { value: "Essays", label: "Essays", count: 322373 },
  { value: "Ethiopia", label: "Ethiopia", count: 1121 },
  { value: "Ethnic", label: "Ethnic", count: 13 },
  { value: "Ethnicity", label: "Ethnicity", count: 6 },
  { value: "Ethnic Studies", label: "Ethnic Studies", count: 7 },
  { value: "Ethnography", label: "Ethnography", count: 1263 },
  { value: "Eugenics", label: "Eugenics", count: 4340 },
  { value: "European History", label: "European History", count: 55468 },
  { value: "European Literature", label: "European Literature", count: 8965 },
  { value: "Evangelism", label: "Evangelism", count: 3712 },
  { value: "Evolution", label: "Evolution", count: 38669 },
  { value: "Fables", label: "Fables", count: 3331 },
  { value: "Fae", label: "Fae", count: 39365 },
  { value: "Fairies", label: "Fairies", count: 12598 },
  { value: "Fairy Tale Retellings", label: "Fairy Tale Retellings", count: 5821 },
  { value: "Fairy Tales", label: "Fairy Tales", count: 171581 },
  { value: "Faith", label: "Faith", count: 210915 },
  { value: "Fake Dating", label: "Fake Dating", count: 12287 },
  { value: "Family", label: "Family", count: 244447 },
  { value: "Family Drama", label: "Family Drama", count: 6655 },
  { value: "Family Law", label: "Family Law", count: 26 },
  { value: "Family Life", label: "Family Life", count: 369 },
  { value: "Fandom", label: "Fandom", count: 1005 },
  { value: "Fan Fiction", label: "Fan Fiction", count: 2539 },
  { value: "Fantasy", label: "Fantasy", count: 2376193 },
  { value: "Fantasy Of Manners", label: "Fantasy Of Manners", count: 148 },
  { value: "Fantasy Romance", label: "Fantasy Romance", count: 42039 },
  { value: "Far Right", label: "Far Right", count: 109 },
  { value: "Fashion", label: "Fashion", count: 7903 },
  { value: "Fashion Design", label: "Fashion Design", count: 221 },
  { value: "Fashion Designers", label: "Fashion Designers", count: 11 },
  { value: "Fashion History", label: "Fashion History", count: 608 },
  { value: "Fat", label: "Fat", count: 275 },
  { value: "Fat Acceptance", label: "Fat Acceptance", count: 112 },
  { value: "Fat Studies", label: "Fat Studies", count: 186 },
  { value: "Favorites", label: "Favorites", count: 2840 },
  { value: "Female Authors", label: "Female Authors", count: 19619 },
  { value: "Feminism", label: "Feminism", count: 188072 },
  { value: "Feminist Studies", label: "Feminist Studies", count: 7 },
  { value: "Feminist Theory", label: "Feminist Theory", count: 843 },
  { value: "Femme Femme", label: "Femme Femme", count: 777 },
  { value: "Femslash", label: "Femslash", count: 5 },
  { value: "F F F", label: "F F F", count: 7 },
  { value: "Fiction", label: "Fiction", count: 7284707 },
  { value: "Field Guides", label: "Field Guides", count: 611 },
  { value: "Fighters", label: "Fighters", count: 4290 },
  { value: "Figure Skating", label: "Figure Skating", count: 269 },
  { value: "Film", label: "Film", count: 27305 },
  { value: "Finance", label: "Finance", count: 80036 },
  { value: "Financial Management", label: "Financial Management", count: 9 },
  { value: "Finnish Literature", label: "Finnish Literature", count: 7365 },
  { value: "Fire Engines", label: "Fire Engines", count: 12 },
  { value: "Firefighters", label: "Firefighters", count: 5392 },
  { value: "Fire Services", label: "Fire Services", count: 130 },
  { value: "Fish Out Of Water", label: "Fish Out Of Water", count: 13 },
  { value: "Fitness", label: "Fitness", count: 11123 },
  { value: "Flash Fiction", label: "Flash Fiction", count: 540 },
  { value: "F M F", label: "F M F", count: 34 },
  { value: "Folklore", label: "Folklore", count: 77166 },
  { value: "Folk Tales", label: "Folk Tales", count: 6756 },
  { value: "Food", label: "Food", count: 81730 },
  { value: "Food and Drink", label: "Food and Drink", count: 15412 },
  { value: "Food and Wine", label: "Food and Wine", count: 1423 },
  { value: "Food History", label: "Food History", count: 1778 },
  { value: "Foodie", label: "Foodie", count: 9433 },
  { value: "Food Preservation", label: "Food Preservation", count: 273 },
  { value: "Food Science", label: "Food Science", count: 254 },
  { value: "Food Writing", label: "Food Writing", count: 5151 },
  { value: "Football", label: "Football", count: 15221 },
  { value: "Forbidden Love", label: "Forbidden Love", count: 6771 },
  { value: "Forbidden Romance", label: "Forbidden Romance", count: 7290 },
  { value: "Forced Proximity", label: "Forced Proximity", count: 33059 },
  { value: "Forgotten Realms", label: "Forgotten Realms", count: 4251 },
  { value: "Foster Children", label: "Foster Children", count: 26 },
  { value: "Fostering", label: "Fostering", count: 2516 },
  { value: "Found Family", label: "Found Family", count: 9480 },
  { value: "Fractured Fairy Tales", label: "Fractured Fairy Tales", count: 1282 },
  { value: "France", label: "France", count: 549584 },
  { value: "Freight", label: "Freight", count: 6 },
  { value: "French Literature", label: "French Literature", count: 318975 },
  { value: "French Revolution", label: "French Revolution", count: 21603 },
  { value: "Friendship", label: "Friendship", count: 99366 },
  { value: "Friends To Lovers", label: "Friends To Lovers", count: 88533 },
  { value: "Frugal", label: "Frugal", count: 31 },
  { value: "Fundamentalism", label: "Fundamentalism", count: 93 },
  { value: "Futurism", label: "Futurism", count: 3015 },
  { value: "Futuristic", label: "Futuristic", count: 10835 },
  { value: "Futuristic Romance", label: "Futuristic Romance", count: 268 },
  { value: "Gamebooks", label: "Gamebooks", count: 930 },
  { value: "Game Design", label: "Game Design", count: 1196 },
  { value: "Games", label: "Games", count: 8366 },
  { value: "Gaming", label: "Gaming", count: 7303 },
  { value: "Gaming Fiction", label: "Gaming Fiction", count: 4 },
  { value: "Gardening", label: "Gardening", count: 13268 },
  { value: "Gaslamp Fantasy", label: "Gaslamp Fantasy", count: 67 },
  { value: "Gastronomy", label: "Gastronomy", count: 1402 },
  { value: "Gay", label: "Gay", count: 54542 },
  { value: "Gay Erotica", label: "Gay Erotica", count: 25 },
  { value: "Gay Fiction", label: "Gay Fiction", count: 3197 },
  { value: "Gay For You", label: "Gay For You", count: 4527 },
  { value: "Geek", label: "Geek", count: 359 },
  { value: "Gemstones", label: "Gemstones", count: 95 },
  { value: "Gender", label: "Gender", count: 27126 },
  { value: "Gender and Sexuality", label: "Gender and Sexuality", count: 1229 },
  { value: "Genderfluid", label: "Genderfluid", count: 124 },
  { value: "Gender Identity", label: "Gender Identity", count: 233 },
  { value: "Genderqueer", label: "Genderqueer", count: 675 },
  { value: "Gender Roles", label: "Gender Roles", count: 232 },
  { value: "Gender Studies", label: "Gender Studies", count: 5478 },
  { value: "Genetics", label: "Genetics", count: 4411 },
  { value: "Geoffrey Chaucer", label: "Geoffrey Chaucer", count: 854 },
  { value: "Geography", label: "Geography", count: 11922 },
  { value: "Geology", label: "Geology", count: 3189 },
  { value: "Geometry", label: "Geometry", count: 601 },
  { value: "Georgian", label: "Georgian", count: 4464 },
  { value: "Georgian Romance", label: "Georgian Romance", count: 308 },
  { value: "German Literature", label: "German Literature", count: 220439 },
  { value: "Germany", label: "Germany", count: 113392 },
  { value: "Gettysburg Campaign", label: "Gettysburg Campaign", count: 4 },
  { value: "Ghana", label: "Ghana", count: 945 },
  { value: "Ghosts", label: "Ghosts", count: 63895 },
  { value: "Ghost Stories", label: "Ghost Stories", count: 13775 },
  { value: "Glaciers", label: "Glaciers", count: 18 },
  { value: "Global Warming", label: "Global Warming", count: 351 },
  { value: "Gnosticism", label: "Gnosticism", count: 872 },
  { value: "Go", label: "Go", count: 660 },
  { value: "God", label: "God", count: 3647 },
  { value: "Goddess", label: "Goddess", count: 723 },
  { value: "Gods", label: "Gods", count: 4336 },
  { value: "Golden Age Mystery", label: "Golden Age Mystery", count: 29535 },
  { value: "Goodreads Choice Awards", label: "Goodreads Choice Awards", count: 97 },
  { value: "Google", label: "Google", count: 2394 },
  { value: "Goth", label: "Goth", count: 150 },
  { value: "Gothic", label: "Gothic", count: 396267 },
  { value: "Gothic Horror", label: "Gothic Horror", count: 3440 },
  { value: "Gothic Romance", label: "Gothic Romance", count: 5055 },
  { value: "Government", label: "Government", count: 14614 },
  { value: "Grad School", label: "Grad School", count: 6783 },
  { value: "Graffiti", label: "Graffiti", count: 142 },
  { value: "Graphica", label: "Graphica", count: 17 },
  { value: "Graphic Literature", label: "Graphic Literature", count: 40 },
  { value: "Graphic Non Fiction", label: "Graphic Non Fiction", count: 85 },
  { value: "Graphic Novels", label: "Graphic Novels", count: 303909 },
  { value: "Graphic Novels Comics", label: "Graphic Novels Comics", count: 128085 },
  { value: "Graphic Novels Comics Manga", label: "Graphic Novels Comics Manga", count: 493 },
  { value: "Graphic Novels Manga", label: "Graphic Novels Manga", count: 9700 },
  { value: "Greece", label: "Greece", count: 73602 },
  { value: "Greek Mythology", label: "Greek Mythology", count: 46339 },
  { value: "Green", label: "Green", count: 1975 },
  { value: "Grief", label: "Grief", count: 21951 },
  { value: "Grimm", label: "Grimm", count: 297 },
  { value: "Gritty", label: "Gritty", count: 229 },
  { value: "Growth Mindset", label: "Growth Mindset", count: 1310 },
  { value: "Guidebook", label: "Guidebook", count: 3342 },
  { value: "Guides", label: "Guides", count: 2642 },
  { value: "Guinea", label: "Guinea", count: 144 },
  { value: "Gynaecology", label: "Gynaecology", count: 28 },
  { value: "Habsburg Empire", label: "Habsburg Empire", count: 20 },
  { value: "Hackers", label: "Hackers", count: 1754 },
  { value: "Halloween", label: "Halloween", count: 24671 },
  { value: "Hard Boiled", label: "Hard Boiled", count: 22110 },
  { value: "Hard Science Fiction", label: "Hard Science Fiction", count: 7077 },
  { value: "Harem", label: "Harem", count: 4721 },
  { value: "Harlequin", label: "Harlequin", count: 39924 },
  { value: "Harlequin Blaze", label: "Harlequin Blaze", count: 1038 },
  { value: "Harlequin Category Romance", label: "Harlequin Category Romance", count: 26 },
  { value: "Harlequin Desire", label: "Harlequin Desire", count: 2352 },
  { value: "Harlequin Heartwarming", label: "Harlequin Heartwarming", count: 42 },
  { value: "Harlequin Historical", label: "Harlequin Historical", count: 1013 },
  { value: "Harlequin Medical Romance", label: "Harlequin Medical Romance", count: 17 },
  { value: "Harlequin Nocturne", label: "Harlequin Nocturne", count: 407 },
  { value: "Harlequin Presents", label: "Harlequin Presents", count: 7642 },
  { value: "Harlequin Romance", label: "Harlequin Romance", count: 8831 },
  { value: "Harlequin Romantic Suspense", label: "Harlequin Romantic Suspense", count: 67 },
  { value: "Harlequin Teen", label: "Harlequin Teen", count: 50 },
  { value: "Harry Potter", label: "Harry Potter", count: 17030 },
  { value: "Heads", label: "Heads", count: 36 },
  { value: "Health", label: "Health", count: 123336 },
  { value: "Health Care", label: "Health Care", count: 3763 },
  { value: "He Falls First", label: "He Falls First", count: 3334 },
  { value: "Herbs", label: "Herbs", count: 1618 },
  { value: "Heritage Preservation", label: "Heritage Preservation", count: 40 },
  { value: "Heroic Fantasy", label: "Heroic Fantasy", count: 2713 },
  { value: "Hierarchy", label: "Hierarchy", count: 5 },
  { value: "High Fantasy", label: "High Fantasy", count: 132118 },
  { value: "High School", label: "High School", count: 101399 },
  { value: "High Society", label: "High Society", count: 51 },
  { value: "Hinduism", label: "Hinduism", count: 14316 },
  { value: "Hip Hop", label: "Hip Hop", count: 1180 },
  { value: "Hispanic", label: "Hispanic", count: 2175 },
  { value: "Historical", label: "Historical", count: 1831200 },
  { value: "Historical Costume", label: "Historical Costume", count: 3 },
  { value: "Historical Drama", label: "Historical Drama", count: 12 },
  { value: "Historical Fantasy", label: "Historical Fantasy", count: 14489 },
  { value: "Historical Fiction", label: "Historical Fiction", count: 2769220 },
  { value: "Historical Mystery", label: "Historical Mystery", count: 63870 },
  { value: "Historical Romance", label: "Historical Romance", count: 261522 },
  { value: "Historical Sewing", label: "Historical Sewing", count: 7 },
  { value: "Historical Thriller", label: "Historical Thriller", count: 201 },
  { value: "History", label: "History", count: 1326202 },
  { value: "History and Politics", label: "History and Politics", count: 1224 },
  { value: "History Of Medicine", label: "History Of Medicine", count: 582 },
  { value: "History Of Science", label: "History Of Science", count: 10272 },
  { value: "Hockey", label: "Hockey", count: 15293 },
  { value: "Hockey Romance", label: "Hockey Romance", count: 10456 },
  { value: "Holiday", label: "Holiday", count: 100624 },
  { value: "Holiday Romance", label: "Holiday Romance", count: 2711 },
  { value: "Holland", label: "Holland", count: 564 },
  { value: "Holocaust", label: "Holocaust", count: 48025 },
  { value: "Home Economics", label: "Home Economics", count: 165 },
  { value: "Home Improvement", label: "Home Improvement", count: 38 },
  { value: "Homeschool", label: "Homeschool", count: 822 },
  { value: "Horror", label: "Horror", count: 618605 },
  { value: "Horror Thriller", label: "Horror Thriller", count: 19145 },
  { value: "Horse Racing", label: "Horse Racing", count: 1906 },
  { value: "Horses", label: "Horses", count: 32266 },
  { value: "Horticulture", label: "Horticulture", count: 555 },
  { value: "Hospitals", label: "Hospitals", count: 122 },
  { value: "How To", label: "How To", count: 24067 },
  { value: "Hqn", label: "Hqn", count: 6200 },
  { value: "Hugo Awards", label: "Hugo Awards", count: 4242 },
  { value: "Huguenots", label: "Huguenots", count: 24 },
  { value: "Human Development", label: "Human Development", count: 1400 },
  { value: "Humanities", label: "Humanities", count: 2082 },
  { value: "Human Resources", label: "Human Resources", count: 350 },
  { value: "Humor", label: "Humor", count: 739399 },
  { value: "Hungarian Literature", label: "Hungarian Literature", count: 5596 },
  { value: "Hungary", label: "Hungary", count: 6455 },
  { value: "Ice Age", label: "Ice Age", count: 16 },
  { value: "Illness", label: "Illness", count: 2236 },
  { value: "India", label: "India", count: 83266 },
  { value: "Indian Literature", label: "Indian Literature", count: 32159 },
  { value: "Indigenous", label: "Indigenous", count: 19740 },
  { value: "Indigenous History", label: "Indigenous History", count: 204 },
  { value: "Indonesian Literature", label: "Indonesian Literature", count: 9545 },
  { value: "Informatics", label: "Informatics", count: 13 },
  { value: "Information Science", label: "Information Science", count: 150 },
  { value: "Inspirational", label: "Inspirational", count: 118129 },
  { value: "Intelligent Design", label: "Intelligent Design", count: 235 },
  { value: "Intensive Care", label: "Intensive Care", count: 158 },
  { value: "Interior Design", label: "Interior Design", count: 624 },
  { value: "International", label: "International", count: 6930 },
  { value: "International Affairs", label: "International Affairs", count: 1184 },
  { value: "International Development", label: "International Development", count: 1848 },
  { value: "International Literature", label: "International Literature", count: 168 },
  { value: "International Relations", label: "International Relations", count: 12296 },
  { value: "Internet", label: "Internet", count: 3212 },
  { value: "Interracial Romance", label: "Interracial Romance", count: 6390 },
  { value: "Intersex", label: "Intersex", count: 143 },
  { value: "Investigative", label: "Investigative", count: 42 },
  { value: "Investigative Journalism", label: "Investigative Journalism", count: 287 },
  { value: "Iran", label: "Iran", count: 15813 },
  { value: "Ireland", label: "Ireland", count: 93196 },
  { value: "Irish Literature", label: "Irish Literature", count: 99430 },
  { value: "Islam", label: "Islam", count: 38712 },
  { value: "Islamic Terrorism", label: "Islamic Terrorism", count: 8 },
  { value: "Islamism", label: "Islamism", count: 184 },
  { value: "Israel", label: "Israel", count: 13793 },
  { value: "Italian Literature", label: "Italian Literature", count: 123822 },
  { value: "Italy", label: "Italy", count: 154330 },
  { value: "Ivory Coast", label: "Ivory Coast", count: 160 },
  { value: "Japan", label: "Japan", count: 81623 },
  { value: "Japanese History", label: "Japanese History", count: 1008 },
  { value: "Japanese Literature", label: "Japanese Literature", count: 59219 },
  { value: "Jaws", label: "Jaws", count: 42 },
  { value: "Jazz", label: "Jazz", count: 2121 },
  { value: "Jewellery", label: "Jewellery", count: 154 },
  { value: "Jewellery Making", label: "Jewellery Making", count: 31 },
  { value: "Jewish", label: "Jewish", count: 53750 },
  { value: "Johannesburg", label: "Johannesburg", count: 17 },
  { value: "Jokes", label: "Jokes", count: 40 },
  { value: "Josei", label: "Josei", count: 4877 },
  { value: "Journal", label: "Journal", count: 2306 },
  { value: "Journaling", label: "Journaling", count: 1176 },
  { value: "Journalism", label: "Journalism", count: 45901 },
  { value: "Judaica", label: "Judaica", count: 5094 },
  { value: "Judaism", label: "Judaism", count: 18583 },
  { value: "Justice", label: "Justice", count: 2347 },
  { value: "Juvenile", label: "Juvenile", count: 258321 },
  { value: "Kazakhstan", label: "Kazakhstan", count: 326 },
  { value: "Kennedy Family", label: "Kennedy Family", count: 305 },
  { value: "Kenya", label: "Kenya", count: 4015 },
  { value: "Kids", label: "Kids", count: 76642 },
  { value: "Knitting", label: "Knitting", count: 4412 },
  { value: "Komik", label: "Komik", count: 3098 },
  { value: "Ku Klux Klan", label: "Ku Klux Klan", count: 2 },
  { value: "Labor", label: "Labor", count: 2166 },
  { value: "Landscape Architecture", label: "Landscape Architecture", count: 49 },
  { value: "Landscaping", label: "Landscaping", count: 17 },
  { value: "Language", label: "Language", count: 39621 },
  { value: "Latina", label: "Latina", count: 207 },
  { value: "Latin American", label: "Latin American", count: 39739 },
  { value: "Latin American History", label: "Latin American History", count: 2661 },
  { value: "Latin American Literature", label: "Latin American Literature", count: 25202 },
  { value: "Latino", label: "Latino", count: 2450 },
  { value: "Latinx", label: "Latinx", count: 11345 },
  { value: "Law", label: "Law", count: 36874 },
  { value: "Lds", label: "Lds", count: 9700 },
  { value: "Lds Fiction", label: "Lds Fiction", count: 3438 },
  { value: "Lds Non Fiction", label: "Lds Non Fiction", count: 1907 },
  { value: "Leadership", label: "Leadership", count: 106749 },
  { value: "Lebanon", label: "Lebanon", count: 6259 },
  { value: "Led Zeppelin", label: "Led Zeppelin", count: 136 },
  { value: "Legal", label: "Legal", count: 23901 },
  { value: "Legal Thriller", label: "Legal Thriller", count: 28288 },
  { value: "Lenin", label: "Lenin", count: 1324 },
  { value: "Leningrad", label: "Leningrad", count: 39 },
  { value: "Lesbian", label: "Lesbian", count: 38529 },
  { value: "Lesbian Fiction", label: "Lesbian Fiction", count: 6985 },
  { value: "Lesbian Romance", label: "Lesbian Romance", count: 7939 },
  { value: "Lesotho", label: "Lesotho", count: 10 },
  { value: "LGBT", label: "LGBT", count: 244049 },
  { value: "LGBT Romance", label: "LGBT Romance", count: 110 },
  { value: "Liberia", label: "Liberia", count: 379 },
  { value: "Librarianship", label: "Librarianship", count: 501 },
  { value: "Library Science", label: "Library Science", count: 615 },
  { value: "Libya", label: "Libya", count: 555 },
  { value: "Lie", label: "Lie", count: 74 },
  { value: "Lifestyle", label: "Lifestyle", count: 3360 },
  { value: "Light Novel", label: "Light Novel", count: 8183 },
  { value: "Linguistics", label: "Linguistics", count: 14441 },
  { value: "Lit Crit", label: "Lit Crit", count: 180 },
  { value: "Literary Criticism", label: "Literary Criticism", count: 32953 },
  { value: "Literary Fiction", label: "Literary Fiction", count: 567337 },
  { value: "Literary Horror", label: "Literary Horror", count: 24 },
  { value: "Literary Thriller", label: "Literary Thriller", count: 12 },
  { value: "Literature", label: "Literature", count: 3315456 },
  { value: "Local History", label: "Local History", count: 179 },
  { value: "Logic", label: "Logic", count: 7285 },
  { value: "London", label: "London", count: 18469 },
  { value: "Lost Love", label: "Lost Love", count: 48 },
  { value: "Love", label: "Love", count: 54028 },
  { value: "Lovecraftian", label: "Lovecraftian", count: 35471 },
  { value: "Love Inspired", label: "Love Inspired", count: 6326 },
  { value: "Love Inspired Historical", label: "Love Inspired Historical", count: 716 },
  { value: "Love Inspired Suspense", label: "Love Inspired Suspense", count: 4114 },
  { value: "Love Story", label: "Love Story", count: 5108 },
  { value: "Loveswept", label: "Loveswept", count: 289 },
  { value: "Low Fantasy", label: "Low Fantasy", count: 290 },
  { value: "Luxemburg", label: "Luxemburg", count: 50 },
  { value: "Madagascar", label: "Madagascar", count: 103 },
  { value: "Mafia Romance", label: "Mafia Romance", count: 20043 },
  { value: "Magic", label: "Magic", count: 405470 },
  { value: "Magical Realism", label: "Magical Realism", count: 79961 },
  { value: "Magick", label: "Magick", count: 6537 },
  { value: "Mail Order Brides", label: "Mail Order Brides", count: 1040 },
  { value: "Malawi", label: "Malawi", count: 220 },
  { value: "Mali", label: "Mali", count: 304 },
  { value: "Management", label: "Management", count: 53231 },
  { value: "Managers", label: "Managers", count: 24 },
  { value: "Manga", label: "Manga", count: 147863 },
  { value: "Manga Romance", label: "Manga Romance", count: 3794 },
  { value: "Manhwa", label: "Manhwa", count: 3113 },
  { value: "Maps", label: "Maps", count: 1268 },
  { value: "Marathi", label: "Marathi", count: 1361 },
  { value: "Maritime", label: "Maritime", count: 13371 },
  { value: "Marriage", label: "Marriage", count: 19128 },
  { value: "Marriage Of Convenience", label: "Marriage Of Convenience", count: 19160 },
  { value: "Martial Arts", label: "Martial Arts", count: 7860 },
  { value: "Marvel", label: "Marvel", count: 23086 },
  { value: "Mary I", label: "Mary I", count: 31 },
  { value: "Mary Shelley", label: "Mary Shelley", count: 1102 },
  { value: "Material Culture", label: "Material Culture", count: 110 },
  { value: "Mathematics", label: "Mathematics", count: 40371 },
  { value: "Mauritania", label: "Mauritania", count: 41 },
  { value: "Mauritius", label: "Mauritius", count: 402 },
  { value: "Media Analysis", label: "Media Analysis", count: 23 },
  { value: "Media Tie In", label: "Media Tie In", count: 41990 },
  { value: "Medical", label: "Medical", count: 59406 },
  { value: "Medical Ethics", label: "Medical Ethics", count: 41 },
  { value: "Medical Profession", label: "Medical Profession", count: 4 },
  { value: "Medicine", label: "Medicine", count: 48740 },
  { value: "Medieval", label: "Medieval", count: 132168 },
  { value: "Medieval History", label: "Medieval History", count: 12202 },
  { value: "Medievalism", label: "Medievalism", count: 43 },
  { value: "Medieval Romance", label: "Medieval Romance", count: 10277 },
  { value: "Meditation", label: "Meditation", count: 23722 },
  { value: "Meet Cute", label: "Meet Cute", count: 65 },
  { value: "Memoir", label: "Memoir", count: 546609 },
  { value: "Menage", label: "Menage", count: 20576 },
  { value: "Mental Health", label: "Mental Health", count: 115860 },
  { value: "Mental Illness", label: "Mental Illness", count: 19522 },
  { value: "Mermaids", label: "Mermaids", count: 11454 },
  { value: "Metaphysics", label: "Metaphysics", count: 53275 },
  { value: "M F F", label: "M F F", count: 130 },
  { value: "M F M", label: "M F M", count: 6131 },
  { value: "M F Romance", label: "M F Romance", count: 29935 },
  { value: "Microhistory", label: "Microhistory", count: 4516 },
  { value: "Middle East", label: "Middle East", count: 75406 },
  { value: "Middle Grade", label: "Middle Grade", count: 727314 },
  { value: "Military Fiction", label: "Military Fiction", count: 225803 },
  { value: "Military History", label: "Military History", count: 77465 },
  { value: "Military Romance", label: "Military Romance", count: 15506 },
  { value: "Military Science Fiction", label: "Military Science Fiction", count: 12070 },
  { value: "Military Thriller", label: "Military Thriller", count: 1659 },
  { value: "Mills and Boon", label: "Mills and Boon", count: 1657 },
  { value: "Mindfullness", label: "Mindfullness", count: 43 },
  { value: "Mine", label: "Mine", count: 757 },
  { value: "Mira", label: "Mira", count: 260 },
  { value: "Mixed Martial Arts", label: "Mixed Martial Arts", count: 2414 },
  { value: "M M Contemporary", label: "M M Contemporary", count: 9462 },
  { value: "M M F", label: "M M F", count: 5465 },
  { value: "M M Fantasy", label: "M M Fantasy", count: 2104 },
  { value: "M M Historical Romance", label: "M M Historical Romance", count: 786 },
  { value: "M M M", label: "M M M", count: 3813 },
  { value: "M M M F", label: "M M M F", count: 3 },
  { value: "M M M M", label: "M M M M", count: 107 },
  { value: "M M Mystery", label: "M M Mystery", count: 413 },
  { value: "Mmorpg", label: "Mmorpg", count: 94 },
  { value: "M M Paranormal", label: "M M Paranormal", count: 3591 },
  { value: "M M Romance", label: "M M Romance", count: 94282 },
  { value: "M M Romantic Suspense", label: "M M Romantic Suspense", count: 40 },
  { value: "M M Science Fiction", label: "M M Science Fiction", count: 333 },
  { value: "M M Shapeshifters", label: "M M Shapeshifters", count: 1717 },
  { value: "M M Sports Romance", label: "M M Sports Romance", count: 1331 },
  { value: "M M Supernatural", label: "M M Supernatural", count: 32 },
  { value: "M M Urban Fantasy", label: "M M Urban Fantasy", count: 4 },
  { value: "M M Young Adult", label: "M M Young Adult", count: 26 },
  { value: "Modern", label: "Modern", count: 11134 },
  { value: "Modern Classics", label: "Modern Classics", count: 23649 },
  { value: "Money", label: "Money", count: 35452 },
  { value: "Money Management", label: "Money Management", count: 392 },
  { value: "Monster Romance", label: "Monster Romance", count: 4163 },
  { value: "Monsters", label: "Monsters", count: 13290 },
  { value: "Morally Gray", label: "Morally Gray", count: 14 },
  { value: "Morally Grey", label: "Morally Grey", count: 179 },
  { value: "Mormonism", label: "Mormonism", count: 3235 },
  { value: "Moroccan", label: "Moroccan", count: 73 },
  { value: "Morocco", label: "Morocco", count: 2558 },
  { value: "Moscow", label: "Moscow", count: 141 },
  { value: "Motorcycle", label: "Motorcycle", count: 4950 },
  { value: "Motorcycling", label: "Motorcycling", count: 365 },
  { value: "Mountaineering", label: "Mountaineering", count: 4239 },
  { value: "Mozambique", label: "Mozambique", count: 674 },
  { value: "Multicultural Literature", label: "Multicultural Literature", count: 482 },
  { value: "Multiple Partners", label: "Multiple Partners", count: 134 },
  { value: "Multiplication", label: "Multiplication", count: 116 },
  { value: "Murder Mystery", label: "Murder Mystery", count: 121918 },
  { value: "Museology", label: "Museology", count: 124 },
  { value: "Museums", label: "Museums", count: 824 },
  { value: "Music", label: "Music", count: 94671 },
  { value: "Musicals", label: "Musicals", count: 1997 },
  { value: "Music Biography", label: "Music Biography", count: 3806 },
  { value: "Musicians", label: "Musicians", count: 9287 },
  { value: "Muslimah", label: "Muslimah", count: 46 },
  { value: "Muslims", label: "Muslims", count: 1575 },
  { value: "Mystery", label: "Mystery", count: 1717656 },
  { value: "Mystery Romance", label: "Mystery Romance", count: 640 },
  { value: "Mystery Thriller", label: "Mystery Thriller", count: 920050 },
  { value: "Mysticism", label: "Mysticism", count: 27314 },
  { value: "Mythical Creatures", label: "Mythical Creatures", count: 214 },
  { value: "Mythology", label: "Mythology", count: 259132 },
  { value: "Nairobi", label: "Nairobi", count: 2 },
  { value: "Namibia", label: "Namibia", count: 482 },
  { value: "Narrative", label: "Narrative", count: 1190 },
  { value: "Native American", label: "Native American", count: 29076 },
  { value: "Native American History", label: "Native American History", count: 1248 },
  { value: "Native Americans", label: "Native Americans", count: 9449 },
  { value: "Natural History", label: "Natural History", count: 40839 },
  { value: "Nature", label: "Nature", count: 189131 },
  { value: "Naturopathy", label: "Naturopathy", count: 126 },
  { value: "Nautical", label: "Nautical", count: 41487 },
  { value: "Naval Historical Fiction", label: "Naval Historical Fiction", count: 1020 },
  { value: "Naval History", label: "Naval History", count: 4840 },
  { value: "Nazi Party", label: "Nazi Party", count: 1915 },
  { value: "Near Future", label: "Near Future", count: 1020 },
  { value: "Nerd", label: "Nerd", count: 428 },
  { value: "Neuroscience", label: "Neuroscience", count: 19407 },
  { value: "New Adult", label: "New Adult", count: 139474 },
  { value: "New Adult Romance", label: "New Adult Romance", count: 2223 },
  { value: "New Age", label: "New Age", count: 18260 },
  { value: "New Testament", label: "New Testament", count: 6996 },
  { value: "New Weird", label: "New Weird", count: 1480 },
  { value: "New York", label: "New York", count: 49102 },
  { value: "Niger", label: "Niger", count: 38 },
  { value: "Nigeria", label: "Nigeria", count: 5191 },
  { value: "Nobel Prize", label: "Nobel Prize", count: 76577 },
  { value: "Noir", label: "Noir", count: 78332 },
  { value: "Nonfiction", label: "Nonfiction", count: 2464620 },
  { value: "Nordic Noir", label: "Nordic Noir", count: 23580 },
  { value: "Norman", label: "Norman", count: 85 },
  { value: "North American History", label: "North American History", count: 23 },
  { value: "Northern Africa", label: "Northern Africa", count: 348 },
  { value: "Novel In Verse", label: "Novel In Verse", count: 3532 },
  { value: "Novella", label: "Novella", count: 141635 },
  { value: "Novels", label: "Novels", count: 2128948 },
  { value: "NSFW", label: "NSFW", count: 215 },
  { value: "Number", label: "Number", count: 3174 },
  { value: "Number Theory", label: "Number Theory", count: 13 },
  { value: "Numeracy", label: "Numeracy", count: 65 },
  { value: "Numerology", label: "Numerology", count: 170 },
  { value: "Numismatics", label: "Numismatics", count: 191 },
  { value: "Nursery Rhymes", label: "Nursery Rhymes", count: 2262 },
  { value: "Nursing", label: "Nursing", count: 3784 },
  { value: "Nutrition", label: "Nutrition", count: 20107 },
  { value: "Occult", label: "Occult", count: 28770 },
  { value: "Occult Detective", label: "Occult Detective", count: 260 },
  { value: "Old Testament", label: "Old Testament", count: 3632 },
  { value: "Omegaverse", label: "Omegaverse", count: 8743 },
  { value: "Oral History", label: "Oral History", count: 1364 },
  { value: "Organizational Culture", label: "Organizational Culture", count: 17 },
  { value: "Organizational Development", label: "Organizational Development", count: 157 },
  { value: "Origami", label: "Origami", count: 18 },
  { value: "Ornithology", label: "Ornithology", count: 1077 },
  { value: "Outdoors", label: "Outdoors", count: 13445 },
  { value: "Outlander", label: "Outlander", count: 2685 },
  { value: "Outlander Series", label: "Outlander Series", count: 888 },
  { value: "Own", label: "Own", count: 8538 },
  { value: "Own Voices", label: "Own Voices", count: 9 },
  { value: "Paganism", label: "Paganism", count: 7488 },
  { value: "Pakistan", label: "Pakistan", count: 5759 },
  { value: "Palaeontology", label: "Palaeontology", count: 1932 },
  { value: "Paramedics", label: "Paramedics", count: 106 },
  { value: "Paranormal", label: "Paranormal", count: 488959 },
  { value: "Paranormal Fiction", label: "Paranormal Fiction", count: 314 },
  { value: "Paranormal Mystery", label: "Paranormal Mystery", count: 4037 },
  { value: "Paranormal Romance", label: "Paranormal Romance", count: 190547 },
  { value: "Paranormal Urban Fantasy", label: "Paranormal Urban Fantasy", count: 1239 },
  { value: "Parenting", label: "Parenting", count: 57756 },
  { value: "Patternmaking", label: "Patternmaking", count: 39 },
  { value: "Peak Oil", label: "Peak Oil", count: 273 },
  { value: "Pediatrics", label: "Pediatrics", count: 35 },
  { value: "Peer Review", label: "Peer Review", count: 88 },
  { value: "Percy Jackson", label: "Percy Jackson", count: 4844 },
  { value: "Period Drama", label: "Period Drama", count: 75 },
  { value: "Personal Development", label: "Personal Development", count: 217090 },
  { value: "Personal Finance", label: "Personal Finance", count: 21313 },
  { value: "Personal Growth", label: "Personal Growth", count: 44936 },
  { value: "Philosophy", label: "Philosophy", count: 1212000 },
  { value: "Photography", label: "Photography", count: 13548 },
  { value: "Physical Therapy", label: "Physical Therapy", count: 256 },
  { value: "Physics", label: "Physics", count: 45982 },
  { value: "Physiotherapy", label: "Physiotherapy", count: 58 },
  { value: "Picture Books", label: "Picture Books", count: 280893 },
  { value: "Pilots", label: "Pilots", count: 374 },
  { value: "Pirates", label: "Pirates", count: 40101 },
  { value: "Planetary Romance", label: "Planetary Romance", count: 4219 },
  { value: "Planetary Science", label: "Planetary Science", count: 41 },
  { value: "Planets", label: "Planets", count: 405 },
  { value: "Plantagenet", label: "Plantagenet", count: 2403 },
  { value: "Plants", label: "Plants", count: 7143 },
  { value: "Plays", label: "Plays", count: 348844 },
  { value: "Plus Size", label: "Plus Size", count: 1696 },
  { value: "Poetry", label: "Poetry", count: 593510 },
  { value: "Poetry Plays", label: "Poetry Plays", count: 6620 },
  { value: "Poland", label: "Poland", count: 18331 },
  { value: "Police", label: "Police", count: 16718 },
  { value: "Police Romance", label: "Police Romance", count: 1 },
  { value: "Polish Literature", label: "Polish Literature", count: 23287 },
  { value: "Political Science", label: "Political Science", count: 124456 },
  { value: "Political Thriller", label: "Political Thriller", count: 7812 },
  { value: "Politics", label: "Politics", count: 653239 },
  { value: "Polyamorous", label: "Polyamorous", count: 468 },
  { value: "Polyamory", label: "Polyamory", count: 4881 },
  { value: "Polyandry", label: "Polyandry", count: 7 },
  { value: "Polygamy", label: "Polygamy", count: 785 },
  { value: "Pop Culture", label: "Pop Culture", count: 20486 },
  { value: "Popular Science", label: "Popular Science", count: 32805 },
  { value: "Pornography", label: "Pornography", count: 204 },
  { value: "Portugal", label: "Portugal", count: 14409 },
  { value: "Portuguese Literature", label: "Portuguese Literature", count: 26427 },
  { value: "Positivism", label: "Positivism", count: 282 },
  { value: "Post Apocalyptic", label: "Post Apocalyptic", count: 60812 },
  { value: "Post Colonial", label: "Post Colonial", count: 637 },
  { value: "Poverty", label: "Poverty", count: 5045 },
  { value: "Prayer", label: "Prayer", count: 16428 },
  { value: "Prehistoric", label: "Prehistoric", count: 2936 },
  { value: "Prehistory", label: "Prehistory", count: 2954 },
  { value: "Pre K", label: "Pre K", count: 3674 },
  { value: "Pre Raphaelite", label: "Pre Raphaelite", count: 37 },
  { value: "Preservation", label: "Preservation", count: 131 },
  { value: "Presidents", label: "Presidents", count: 27345 },
  { value: "Princesses", label: "Princesses", count: 2331 },
  { value: "Procedural", label: "Procedural", count: 34894 },
  { value: "Productivity", label: "Productivity", count: 35921 },
  { value: "Professional Development", label: "Professional Development", count: 17649 },
  { value: "Professors", label: "Professors", count: 134 },
  { value: "Programming", label: "Programming", count: 15197 },
  { value: "Programming Languages", label: "Programming Languages", count: 279 },
  { value: "Prostitution", label: "Prostitution", count: 681 },
  { value: "Pseudoscience", label: "Pseudoscience", count: 444 },
  { value: "Psychiatry", label: "Psychiatry", count: 5319 },
  { value: "Psychoanalysis", label: "Psychoanalysis", count: 18263 },
  { value: "Psychological Drama", label: "Psychological Drama", count: 41 },
  { value: "Psychological Horror", label: "Psychological Horror", count: 55 },
  { value: "Psychological Suspense", label: "Psychological Suspense", count: 359 },
  { value: "Psychological Thriller", label: "Psychological Thriller", count: 38894 },
  { value: "Psychology", label: "Psychology", count: 477431 },
  { value: "Public Policy", label: "Public Policy", count: 682 },
  { value: "Pulp", label: "Pulp", count: 107266 },
  { value: "Pulp Adventure", label: "Pulp Adventure", count: 1452 },
  { value: "Pulp Noir", label: "Pulp Noir", count: 131 },
  { value: "Punk", label: "Punk", count: 2175 },
  { value: "Punx", label: "Punx", count: 3 },
  { value: "Puzzles", label: "Puzzles", count: 982 },
  { value: "Qualitative Research", label: "Qualitative Research", count: 125 },
  { value: "Quantum Mechanics", label: "Quantum Mechanics", count: 2590 },
  { value: "Queer", label: "Queer", count: 148618 },
  { value: "Queer Fantasy", label: "Queer Fantasy", count: 53 },
  { value: "Queer Lit", label: "Queer Lit", count: 2466 },
  { value: "Queer Romance", label: "Queer Romance", count: 346 },
  { value: "Queer Studies", label: "Queer Studies", count: 344 },
  { value: "Quilting", label: "Quilting", count: 2119 },
  { value: "Rabbits", label: "Rabbits", count: 5447 },
  { value: "Race", label: "Race", count: 95038 },
  { value: "Racing", label: "Racing", count: 1411 },
  { value: "Rags To Riches", label: "Rags To Riches", count: 61 },
  { value: "Railways", label: "Railways", count: 665 },
  { value: "Read For College", label: "Read For College", count: 217 },
  { value: "Read For School", label: "Read For School", count: 206709 },
  { value: "Realistic Fiction", label: "Realistic Fiction", count: 166504 },
  { value: "Realistic Young Adult", label: "Realistic Young Adult", count: 8 },
  { value: "Real Person Fiction", label: "Real Person Fiction", count: 1 },
  { value: "Recreation", label: "Recreation", count: 444 },
  { value: "Recruitment", label: "Recruitment", count: 221 },
  { value: "Reference", label: "Reference", count: 296569 },
  { value: "Regency", label: "Regency", count: 90724 },
  { value: "Regency Romance", label: "Regency Romance", count: 57568 },
  { value: "Relationships", label: "Relationships", count: 55110 },
  { value: "Religion", label: "Religion", count: 668435 },
  { value: "Renaissance", label: "Renaissance", count: 20816 },
  { value: "Renaissance Studies", label: "Renaissance Studies", count: 23 },
  { value: "Reportage", label: "Reportage", count: 3115 },
  { value: "Republic Of The Congo", label: "Republic Of The Congo", count: 47 },
  { value: "Research", label: "Research", count: 22991 },
  { value: "Research Methods", label: "Research Methods", count: 282 },
  { value: "Retellings", label: "Retellings", count: 43315 },
  { value: "Reverse Harem", label: "Reverse Harem", count: 22631 },
  { value: "Road Trip", label: "Road Trip", count: 3046 },
  { value: "Robots", label: "Robots", count: 6124 },
  { value: "Rock Climbing", label: "Rock Climbing", count: 91 },
  { value: "Rock N Roll", label: "Rock N Roll", count: 7262 },
  { value: "Role Playing Games", label: "Role Playing Games", count: 4209 },
  { value: "Roller Derby", label: "Roller Derby", count: 88 },
  { value: "Roman", label: "Roman", count: 225931 },
  { value: "Roman Britain", label: "Roman Britain", count: 560 },
  { value: "Romance", label: "Romance", count: 2532035 },
  { value: "Roman History", label: "Roman History", count: 12820 },
  { value: "Romania", label: "Romania", count: 6552 },
  { value: "Romanian Literature", label: "Romanian Literature", count: 6207 },
  { value: "Romanovs", label: "Romanovs", count: 1138 },
  { value: "Romantasy", label: "Romantasy", count: 35761 },
  { value: "Romantic", label: "Romantic", count: 5499 },
  { value: "Romantic Comedy", label: "Romantic Comedy", count: 8268 },
  { value: "Romanticism", label: "Romanticism", count: 26300 },
  { value: "Romantic Mystery", label: "Romantic Mystery", count: 79 },
  { value: "Romantic Suspense", label: "Romantic Suspense", count: 138287 },
  { value: "Romantic Thriller", label: "Romantic Thriller", count: 62 },
  { value: "Rom Com", label: "Rom Com", count: 17756 },
  { value: "Royal Air Force", label: "Royal Air Force", count: 190 },
  { value: "Royal Romance", label: "Royal Romance", count: 1053 },
  { value: "Royalty", label: "Royalty", count: 35452 },
  { value: "Rus", label: "Rus", count: 1502 },
  { value: "Russia", label: "Russia", count: 241301 },
  { value: "Russian Empire", label: "Russian Empire", count: 32 },
  { value: "Russian History", label: "Russian History", count: 9779 },
  { value: "Russian Literature", label: "Russian Literature", count: 184059 },
  { value: "Russian Revolution", label: "Russian Revolution", count: 2377 },
  { value: "Rwanda", label: "Rwanda", count: 1358 },
  { value: "Sao Tome and Principe", label: "Sao Tome and Principe", count: 39 },
  { value: "Satanism", label: "Satanism", count: 537 },
  { value: "Satire", label: "Satire", count: 92336 },
  { value: "Scandinavian Literature", label: "Scandinavian Literature", count: 68111 },
  { value: "School", label: "School", count: 1079750 },
  { value: "School Stories", label: "School Stories", count: 8220 },
  { value: "Science", label: "Science", count: 390305 },
  { value: "Science Fiction", label: "Science Fiction", count: 821512 },
  { value: "Science Fiction Fantasy", label: "Science Fiction Fantasy", count: 388393 },
  { value: "Science Fiction Romance", label: "Science Fiction Romance", count: 16237 },
  { value: "Science Nature", label: "Science Nature", count: 10005 },
  { value: "Scientific Method", label: "Scientific Method", count: 9 },
  { value: "Sci Fi Fantasy", label: "Sci Fi Fantasy", count: 2959 },
  { value: "Scores", label: "Scores", count: 68 },
  { value: "Scotland", label: "Scotland", count: 85906 },
  { value: "Scripture", label: "Scripture", count: 7651 },
  { value: "Second Chance", label: "Second Chance", count: 65354 },
  { value: "Second Chance Romance", label: "Second Chance Romance", count: 23635 },
  { value: "Seinen", label: "Seinen", count: 23865 },
  { value: "Self Building", label: "Self Building", count: 22 },
  { value: "Self Esteem", label: "Self Esteem", count: 3401 },
  { value: "Self Help", label: "Self Help", count: 419130 },
  { value: "Self Reliance", label: "Self Reliance", count: 590 },
  { value: "Semiotics", label: "Semiotics", count: 986 },
  { value: "Senegal", label: "Senegal", count: 519 },
  { value: "Sequential Art", label: "Sequential Art", count: 7354 },
  { value: "Serbian Literature", label: "Serbian Literature", count: 3072 },
  { value: "Serial Killer", label: "Serial Killer", count: 11540 },
  { value: "Sewing", label: "Sewing", count: 1341 },
  { value: "Sex and Erotica", label: "Sex and Erotica", count: 4 },
  { value: "Sexuality", label: "Sexuality", count: 16424 },
  { value: "Sex Work", label: "Sex Work", count: 766 },
  { value: "Shakespeare", label: "Shakespeare", count: 185550 },
  { value: "Shapeshifters", label: "Shapeshifters", count: 78927 },
  { value: "Shojo", label: "Shojo", count: 27650 },
  { value: "Shonen", label: "Shonen", count: 46797 },
  { value: "Short Stories", label: "Short Stories", count: 909502 },
  { value: "Short Story Collection", label: "Short Story Collection", count: 19905 },
  { value: "Shounen Ai", label: "Shounen Ai", count: 554 },
  { value: "Sierra Leone", label: "Sierra Leone", count: 284 },
  { value: "Siglo De Oro", label: "Siglo De Oro", count: 589 },
  { value: "Silhouette", label: "Silhouette", count: 869 },
  { value: "Singularity", label: "Singularity", count: 554 },
  { value: "Skeletons", label: "Skeletons", count: 31 },
  { value: "Skepticism", label: "Skepticism", count: 2069 },
  { value: "Slash Fiction", label: "Slash Fiction", count: 66 },
  { value: "Sleuth", label: "Sleuth", count: 82 },
  { value: "Slice Of Life", label: "Slice Of Life", count: 22474 },
  { value: "Slow Burn", label: "Slow Burn", count: 23672 },
  { value: "Slow Burn Romance", label: "Slow Burn Romance", count: 87 },
  { value: "Small Business", label: "Small Business", count: 268 },
  { value: "Small Town Romance", label: "Small Town Romance", count: 25984 },
  { value: "Smut", label: "Smut", count: 35228 },
  { value: "Soccer", label: "Soccer", count: 4914 },
  { value: "Social", label: "Social", count: 7659 },
  { value: "Social Change", label: "Social Change", count: 597 },
  { value: "Social Commentary", label: "Social Commentary", count: 673 },
  { value: "Social Issues", label: "Social Issues", count: 6950 },
  { value: "Social Justice", label: "Social Justice", count: 46497 },
  { value: "Social Media", label: "Social Media", count: 2301 },
  { value: "Social Movements", label: "Social Movements", count: 174 },
  { value: "Social Science", label: "Social Science", count: 28847 },
  { value: "Social Welfare", label: "Social Welfare", count: 15 },
  { value: "Social Work", label: "Social Work", count: 4951 },
  { value: "Society", label: "Society", count: 31835 },
  { value: "Sociology", label: "Sociology", count: 190101 },
  { value: "Software", label: "Software", count: 10219 },
  { value: "Solarpunk", label: "Solarpunk", count: 275 },
  { value: "Soldiers", label: "Soldiers", count: 258 },
  { value: "Somalia", label: "Somalia", count: 897 },
  { value: "South Africa", label: "South Africa", count: 10336 },
  { value: "Southern", label: "Southern", count: 53207 },
  { value: "Southern Africa", label: "Southern Africa", count: 180 },
  { value: "Southern Gothic", label: "Southern Gothic", count: 20436 },
  { value: "South Sudan", label: "South Sudan", count: 88 },
  { value: "Soviet History", label: "Soviet History", count: 1108 },
  { value: "Soviet Union", label: "Soviet Union", count: 3328 },
  { value: "Space", label: "Space", count: 78144 },
  { value: "Space Opera", label: "Space Opera", count: 77492 },
  { value: "Spain", label: "Spain", count: 74840 },
  { value: "Spanish Civil War", label: "Spanish Civil War", count: 3111 },
  { value: "Spanish History", label: "Spanish History", count: 1135 },
  { value: "Spanish Literature", label: "Spanish Literature", count: 126353 },
  { value: "Speculative Fiction", label: "Speculative Fiction", count: 127454 },
  { value: "Spicy Romance", label: "Spicy Romance", count: 351 },
  { value: "Spider Man", label: "Spider Man", count: 3385 },
  { value: "Spiritualism", label: "Spiritualism", count: 1326 },
  { value: "Spirituality", label: "Spirituality", count: 421681 },
  { value: "Splatterpunk", label: "Splatterpunk", count: 2902 },
  { value: "Sports", label: "Sports", count: 116870 },
  { value: "Sports Romance", label: "Sports Romance", count: 40467 },
  { value: "Spy Thriller", label: "Spy Thriller", count: 33956 },
  { value: "Stand Up", label: "Stand Up", count: 232 },
  { value: "Star Crossed", label: "Star Crossed", count: 33 },
  { value: "Star Trek", label: "Star Trek", count: 8444 },
  { value: "Star Trek Deep Space Nine", label: "Star Trek Deep Space Nine", count: 1448 },
  { value: "Star Trek Enterprise", label: "Star Trek Enterprise", count: 210 },
  { value: "Star Trek Original Series", label: "Star Trek Original Series", count: 2120 },
  { value: "Star Trek The Next Generation", label: "Star Trek The Next Generation", count: 1998 },
  { value: "Star Trek Voyager", label: "Star Trek Voyager", count: 569 },
  { value: "Startup", label: "Startup", count: 4966 },
  { value: "Star Wars", label: "Star Wars", count: 13084 },
  { value: "Steampunk", label: "Steampunk", count: 36688 },
  { value: "Steampunk Romance", label: "Steampunk Romance", count: 23 },
  { value: "Steamy Romance", label: "Steamy Romance", count: 531 },
  { value: "Stem", label: "Stem", count: 15843 },
  { value: "Stories", label: "Stories", count: 714 },
  { value: "Storytime", label: "Storytime", count: 76273 },
  { value: "St Petersburg", label: "St Petersburg", count: 6 },
  { value: "Street Art", label: "Street Art", count: 115 },
  { value: "Strippers", label: "Strippers", count: 69 },
  { value: "Strong Female", label: "Strong Female", count: 316 },
  { value: "Strong Female Lead", label: "Strong Female Lead", count: 270 },
  { value: "Stuart", label: "Stuart", count: 189 },
  { value: "Students", label: "Students", count: 24 },
  { value: "Subtraction", label: "Subtraction", count: 12 },
  { value: "Sudan", label: "Sudan", count: 1174 },
  { value: "Suisse", label: "Suisse", count: 115 },
  { value: "Summer", label: "Summer", count: 26425 },
  { value: "Summer Reads", label: "Summer Reads", count: 11058 },
  { value: "Summer Romance", label: "Summer Romance", count: 69 },
  { value: "Superheroes", label: "Superheroes", count: 50340 },
  { value: "Superman", label: "Superman", count: 3298 },
  { value: "Supernatural", label: "Supernatural", count: 194011 },
  { value: "Supernatural Romance", label: "Supernatural Romance", count: 346 },
  { value: "Superstition", label: "Superstition", count: 12 },
  { value: "Surprise Pregnancy", label: "Surprise Pregnancy", count: 2886 },
  { value: "Surreal", label: "Surreal", count: 1842 },
  { value: "Survival", label: "Survival", count: 45514 },
  { value: "Suspense", label: "Suspense", count: 588342 },
  { value: "Sustainability", label: "Sustainability", count: 10476 },
  { value: "Swashbuckling", label: "Swashbuckling", count: 4675 },
  { value: "Swaziland", label: "Swaziland", count: 10 },
  { value: "Sweden", label: "Sweden", count: 30003 },
  { value: "Swedish Literature", label: "Swedish Literature", count: 34082 },
  { value: "Sword and Planet", label: "Sword and Planet", count: 15274 },
  { value: "Sword and Sorcery", label: "Sword and Sorcery", count: 15492 },
  { value: "Syrian Civil War", label: "Syrian Civil War", count: 37 },
  { value: "Tanzania", label: "Tanzania", count: 767 },
  { value: "Taoism", label: "Taoism", count: 6188 },
  { value: "Tarot", label: "Tarot", count: 1143 },
  { value: "Tasmania", label: "Tasmania", count: 1048 },
  { value: "Taxation", label: "Taxation", count: 219 },
  { value: "Tea", label: "Tea", count: 3545 },
  { value: "Teachers", label: "Teachers", count: 4231 },
  { value: "Teaching", label: "Teaching", count: 23023 },
  { value: "Technical", label: "Technical", count: 16935 },
  { value: "Technology", label: "Technology", count: 55838 },
  { value: "Teen", label: "Teen", count: 101322 },
  { value: "Teeth", label: "Teeth", count: 52 },
  { value: "Terrorism", label: "Terrorism", count: 8787 },
  { value: "Textbooks", label: "Textbooks", count: 41965 },
  { value: "Thanksgiving", label: "Thanksgiving", count: 2674 },
  { value: "The Americas", label: "The Americas", count: 2760 },
  { value: "Theatre", label: "Theatre", count: 304608 },
  { value: "The Gambia", label: "The Gambia", count: 18 },
  { value: "Thelema", label: "Thelema", count: 1424 },
  { value: "Theology", label: "Theology", count: 259287 },
  { value: "Theory", label: "Theory", count: 117026 },
  { value: "Theosophy", label: "Theosophy", count: 1933 },
  { value: "The United States Of America", label: "The United States Of America", count: 138945 },
  { value: "The World", label: "The World", count: 4325 },
  { value: "Threesome", label: "Threesome", count: 168 },
  { value: "Thriller", label: "Thriller", count: 1021198 },
  { value: "Thriller Suspense", label: "Thriller Suspense", count: 17451 },
  { value: "Time Travel", label: "Time Travel", count: 90547 },
  { value: "Time Travel Romance", label: "Time Travel Romance", count: 3341 },
  { value: "Togo", label: "Togo", count: 66 },
  { value: "Traditional Chinese Medicine", label: "Traditional Chinese Medicine", count: 149 },
  { value: "Traditional Regency", label: "Traditional Regency", count: 776 },
  { value: "Tragedy", label: "Tragedy", count: 18715 },
  { value: "Trains", label: "Trains", count: 2430 },
  { value: "Transgender", label: "Transgender", count: 5873 },
  { value: "Transgender Romance", label: "Transgender Romance", count: 8 },
  { value: "Translated Fiction", label: "Translated Fiction", count: 1237 },
  { value: "Transport", label: "Transport", count: 5996 },
  { value: "Travel", label: "Travel", count: 227984 },
  { value: "Travelogue", label: "Travelogue", count: 7184 },
  { value: "Trivia", label: "Trivia", count: 2199 },
  { value: "Trucks", label: "Trucks", count: 1356 },
  { value: "True Crime", label: "True Crime", count: 58112 },
  { value: "True Story", label: "True Story", count: 7285 },
  { value: "Tudor Period", label: "Tudor Period", count: 11570 },
  { value: "Tunisia", label: "Tunisia", count: 178 },
  { value: "Turkish", label: "Turkish", count: 11171 },
  { value: "Turkish Literature", label: "Turkish Literature", count: 10122 },
  { value: "Tv", label: "Tv", count: 8549 },
  { value: "Uganda", label: "Uganda", count: 634 },
  { value: "Ukraine", label: "Ukraine", count: 8746 },
  { value: "Ukrainian Literature", label: "Ukrainian Literature", count: 2426 },
  { value: "Underground Railway", label: "Underground Railway", count: 31 },
  { value: "Unfinished", label: "Unfinished", count: 89078 },
  { value: "Unicorns", label: "Unicorns", count: 2651 },
  { value: "United States", label: "United States", count: 13647 },
  { value: "Upstairs Downstairs", label: "Upstairs Downstairs", count: 10 },
  { value: "Urban", label: "Urban", count: 13572 },
  { value: "Urban Design", label: "Urban Design", count: 542 },
  { value: "Urban Fantasy", label: "Urban Fantasy", count: 216395 },
  { value: "Urban Fantasy Romance", label: "Urban Fantasy Romance", count: 21 },
  { value: "Urbanism", label: "Urbanism", count: 4133 },
  { value: "Urban Legends", label: "Urban Legends", count: 88 },
  { value: "Urban Planning", label: "Urban Planning", count: 3195 },
  { value: "Urban Studies", label: "Urban Studies", count: 2144 },
  { value: "Usability", label: "Usability", count: 523 },
  { value: "Us Air Force", label: "Us Air Force", count: 22 },
  { value: "Us Presidents", label: "Us Presidents", count: 6574 },
  { value: "Utopia", label: "Utopia", count: 1020 },
  { value: "Vacation Reads", label: "Vacation Reads", count: 11 },
  { value: "Vaccines", label: "Vaccines", count: 265 },
  { value: "Vampire Hunters", label: "Vampire Hunters", count: 17 },
  { value: "Vampire Romance", label: "Vampire Romance", count: 2437 },
  { value: "Vampires", label: "Vampires", count: 147905 },
  { value: "Vegan", label: "Vegan", count: 5180 },
  { value: "Vegetarian", label: "Vegetarian", count: 2056 },
  { value: "Vegetarianism", label: "Vegetarianism", count: 125 },
  { value: "Vespa", label: "Vespa", count: 12 },
  { value: "Victor Frankenstein", label: "Victor Frankenstein", count: 887 },
  { value: "Victorian", label: "Victorian", count: 403770 },
  { value: "Victorian Romance", label: "Victorian Romance", count: 298 },
  { value: "Video Games", label: "Video Games", count: 8851 },
  { value: "Viking Romance", label: "Viking Romance", count: 838 },
  { value: "Virtual Reality", label: "Virtual Reality", count: 954 },
  { value: "Visual Art", label: "Visual Art", count: 1357 },
  { value: "Walking", label: "Walking", count: 6043 },
  { value: "War", label: "War", count: 441544 },
  { value: "Warcraft", label: "Warcraft", count: 1136 },
  { value: "Warriors", label: "Warriors", count: 331 },
  { value: "Wattpad", label: "Wattpad", count: 2 },
  { value: "Web", label: "Web", count: 2411 },
  { value: "Webcomic", label: "Webcomic", count: 2168 },
  { value: "Website Design", label: "Website Design", count: 1700 },
  { value: "Weird Fiction", label: "Weird Fiction", count: 47875 },
  { value: "Weird West", label: "Weird West", count: 569 },
  { value: "Werecats", label: "Werecats", count: 7 },
  { value: "Werewolves", label: "Werewolves", count: 36423 },
  { value: "Western Africa", label: "Western Africa", count: 612 },
  { value: "Western Historical Romance", label: "Western Historical Romance", count: 5020 },
  { value: "Western Romance", label: "Western Romance", count: 20648 },
  { value: "Westerns", label: "Westerns", count: 167793 },
  { value: "Western Sahara", label: "Western Sahara", count: 35 },
  { value: "Whodunit", label: "Whodunit", count: 1578 },
  { value: "Wholesome", label: "Wholesome", count: 70 },
  { value: "Why Choose", label: "Why Choose", count: 22793 },
  { value: "Wicca", label: "Wicca", count: 3619 },
  { value: "Wilderness", label: "Wilderness", count: 878 },
  { value: "Wildlife", label: "Wildlife", count: 2820 },
  { value: "Wine", label: "Wine", count: 1828 },
  { value: "Witchcraft", label: "Witchcraft", count: 9960 },
  { value: "Witches", label: "Witches", count: 57459 },
  { value: "Witty Banter", label: "Witty Banter", count: 61 },
  { value: "Wizards", label: "Wizards", count: 404 },
  { value: "Wolves", label: "Wolves", count: 7200 },
  { value: "Womens", label: "Womens", count: 119400 },
  { value: "Womens Fiction", label: "Womens Fiction", count: 56456 },
  { value: "Womens Rights", label: "Womens Rights", count: 94 },
  { value: "Womens Sports", label: "Womens Sports", count: 10 },
  { value: "Womens Studies", label: "Womens Studies", count: 3288 },
  { value: "Wonder Woman", label: "Wonder Woman", count: 994 },
  { value: "Woodwork", label: "Woodwork", count: 397 },
  { value: "Words", label: "Words", count: 2572 },
  { value: "Workplace", label: "Workplace", count: 5233 },
  { value: "Workplace Romance", label: "Workplace Romance", count: 9587 },
  { value: "World History", label: "World History", count: 59507 },
  { value: "World Literature", label: "World Literature", count: 3255 },
  { value: "World Of Darkness", label: "World Of Darkness", count: 72 },
  { value: "World Of Warcraft", label: "World Of Warcraft", count: 1113 },
  { value: "World War I", label: "World War I", count: 33042 },
  { value: "World War II", label: "World War II", count: 148798 },
  { value: "Writing", label: "Writing", count: 77728 },
  { value: "Wwii Fiction", label: "Wwii Fiction", count: 982 },
  { value: "X Men", label: "X Men", count: 4184 },
  { value: "YA Horror", label: "YA Horror", count: 739 },
  { value: "Yaoi", label: "Yaoi", count: 6981 },
  { value: "YA Romantasy", label: "YA Romantasy", count: 20 },
  { value: "Yeti", label: "Yeti", count: 37 },
  { value: "Young Adult", label: "Young Adult", count: 1385770 },
  { value: "Young Adult Contemporary", label: "Young Adult Contemporary", count: 23954 },
  { value: "Young Adult Fantasy", label: "Young Adult Fantasy", count: 71199 },
  { value: "Young Adult Historical Fiction", label: "Young Adult Historical Fiction", count: 2146 },
  { value: "Young Adult Horror", label: "Young Adult Horror", count: 17 },
  { value: "Young Adult Mystery", label: "Young Adult Mystery", count: 48 },
  { value: "Young Adult Paranormal", label: "Young Adult Paranormal", count: 1292 },
  { value: "Young Adult Romance", label: "Young Adult Romance", count: 14214 },
  { value: "Young Adult Science Fiction", label: "Young Adult Science Fiction", count: 1360 },
  { value: "Young Readers", label: "Young Readers", count: 3414 },
  { value: "Yuri", label: "Yuri", count: 1743 },
  { value: "Zambia", label: "Zambia", count: 413 },
  { value: "Zen", label: "Zen", count: 7701 },
  { value: "Zimbabwe", label: "Zimbabwe", count: 1614 },
  { value: "Zombies", label: "Zombies", count: 24597 },
  { value: "漫画", label: "漫画", count: 1802 },
];
